site_name: Privateer
theme: readthedocs

nav:
  - Home: index.md
  - About: about.md



- 'HOME': 'index.md'
- 'BASICS':
  - 'Getting Started': 'basics/getting_started.md'
  - 'Compile-time Options': 'basics/compile_time_options.md'
- 'ADVANCED BUILD':
  - 'Build Executables': 'advanced_build/cmake.md'
  - 'Use Umap': 'advanced_build/umap.md'
  - 'Test Metall': 'advanced_build/test.md'
- 'Metall 101':
  - 'Introduction': 'detail/introduction.md'
  - 'API': 'detail/api.md'
  - 'Data Store ls': 'detail/ls.md'
  - 'Pointers in Persistent Memory': 'detail/pointer.md'
  - 'Persistence Policy': 'detail/persistence_policy.md'
  - 'Snapshot': 'detail/snapshot.md'
  - 'Example': 'detail/example.md'
  - 'Internal Architecture': 'detail/internal_architecture.md'
- 'External':
    - 'Open Source Projects Using Metall': 'external/list.md'
    - 'Use Ripples with Metall': 'external/ripples.md'
- 'ABOUT':
  - 'Publication': 'about/publication.md'
  - 'License and Notice': 'about/license_notice.md'
