site_name: Privateer
theme: readthedocs

nav:
- 'HOME': 'index.md'
- 'BASICS':
  - 'Getting Started': 'basics/getting_started.md'
- 'ADVANCED BUILD':
  - 'Build Executables': 'advanced_build/cmake.md'
  - 'Test Metall': 'advanced_build/test.md'
- 'Metall 101':
  - 'Introduction': 'detail/introduction.md'
  - 'API': 'detail/api.md'
- 'ABOUT':
  - 'Publication': 'about/publication.md'
  - 'License and Notice': 'about/license_notice.md'
